### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by jean-francoisgiraud** [sebischair/bbse#4]
Hello, 

Please note the following improvement recommendation in 11_Hyperledger_I.pdf on page 35.

IS: Hyperledger Fabric uses the terms ”Smart Contracts” and ”Chaincode ”. 

WAS: In Hyperledger Fabric, uses the terms ”Smart Contracts” and ”Chaincode ”.

**Comment by UliGall** [comment]
Thank you, we will fix this in the next release.

**Comment by UliGall** [comment]
Hi,

thank you again for pointing it out. We fixed in the current release.

Best
Uli
