### ISSUE TITLE
Proposal for Integration

### ISSUE THREAD

**Issue by jdsika** [sebischair/bbse#5]
Hi @UliGall 

we have released the following [press release](https://asc-s.de/en/news/152/first-results-of-envited-ecosystem-work-group-pulished/) with a "Tezos Deep Dive Deck" regarding the perks of public blockchains in our automotive use case.

At least they could be very interesting for you or your students personally because it is the most comprehensive collection of infroamtion on Tezos to my knowledge.
At best you can integrate them into your lesson material and I could offer to give a "motivational introduction into an automotive usecase" for the students if you think it is interesting for the students?

The slides have been released under CC BY 4.0. 

Best regards
Carlo

**Comment by UliGall** [comment]
Hi Carlo,

thanks for the proposal. It was too late for the 2020 version, however I'm going to bring this up to our team for 2021.

Best
Uli
