### ISSUE TITLE
slide deck: 09_Ethereum_Design_Patterns.pdf - enumeration mistake

### ISSUE THREAD

**Issue by phzeller** [sebischair/bbse#6]
Hi @UliGall,

I've just observed a minor mistake in the outline of [this slide deck](https://github.com/sebischair/bbse/blob/master/slides/09_Ethereum_Design_Patterns.pdf) (namely: p. 2, 11, and 32).
The chapter about token standards should be 3. instead of 2.

**Comment by UliGall** [comment]
Hi, thanks for noticing! We will update that with the next version!

**Comment by UliGall** [comment]
We fixed this in the current version, thank you for pointing out!
